const SETTING_ID = 'id';
const SETTING_PLACEHOLDER = 'placeholder';
const SETTING_ELEMENT = 'element';
const SETTING_TOP = 'top';
const SETTING_LEFT = 'left';
const SETTING_WIDTH = 'width';
const SETTING_SPELLCHECK = 'spellcheck';
const SETTING_ROWS = 'rows';
const SETTING_FONTSIZE = 'fontSize';
const SETTING_DATADIRECTORY = "dataDirectory";
const SETTING_DATAID = "data_id";
const SETTING_TEXTALIGN = 'textAlign';

const SETTING_COMMON_POSITION = 'position';
const SETTING_COMMON_BORDERWIDTH = 'borderWidth';
const SETTING_COMMON_BACKGROUND = 'background';
const SETTING_COMMON_FONTSIZE = 'fontSize';
const SETTING_COMMON_LINEHEIGHT = 'lineHeight';
const SETTING_COMMON_RESIZE = 'resize';
const SETTING_COMMON_OVERFLOW = 'overflow';
const SETTING_COMMON_FONTFAMILY = 'fontFamily';

const SCALEUP_MODE = "scaleup";
const ORIGIN_MODE = "origin";

export  {
    SETTING_ID,
    SETTING_PLACEHOLDER,
    SETTING_ELEMENT,
    SETTING_TOP,
    SETTING_LEFT,
    SETTING_WIDTH,
    SETTING_SPELLCHECK,
    SETTING_ROWS,
    SETTING_FONTSIZE,
    SETTING_DATADIRECTORY,
    SETTING_DATAID,
    SETTING_TEXTALIGN,

    SETTING_COMMON_POSITION,
    SETTING_COMMON_BORDERWIDTH,
    SETTING_COMMON_BACKGROUND,
    SETTING_COMMON_FONTSIZE,
    SETTING_COMMON_LINEHEIGHT,
    SETTING_COMMON_RESIZE,
    SETTING_COMMON_OVERFLOW,
    SETTING_COMMON_FONTFAMILY,

    SCALEUP_MODE,
    ORIGIN_MODE
}