
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import "css/tailwind.css";
import "css/main.css";
import "css/layouts/layout-1.css";
import "css/layouts/e-commerce.css";
import "css/animate.css";
import "css/components/left-sidebar-1/styles-lg.css";
import "css/components/left-sidebar-1/styles-sm.css";
import "css/components/nprogress.css";
import "css/components/recharts.css";
import "css/components/steps.css";
import "css/components/left-sidebar-3.css";
import "css/ag-grid/ag-grid.css";
import "css/ag-grid/ag-theme-custom.css";
import "css/ag-grid/ag-theme-alpine.css";
import "css/ag-grid/ag-theme-balham.css";
import "css/ag-grid/ag-theme-material.css";
import "css/vendors/ReactToastify.css";

import 'react-quill/dist/quill.snow.css';

import  Layout from 'layouts/page'
import { Suspense } from "react";

import { log } from '@repo/kwe-lib-new';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "KREAM" + (process.env.NEXT_PUBLIC_KREAM_API_URL === "http://dev-api-kream.web.kwe.co.kr" ? "-Test Server" : ""),
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          {/* <AuthProvider> */}
          <Suspense>
            <Layout>
              {children}
            </Layout>
          </Suspense>
          {/* </AuthProvider> */}
        </body>
      </html>
    </>
  );
}
